# Generated by Django 5.1.3 on 2025-12-04 09:14

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('color', models.CharField(choices=[('bg-red-500', '赤（入試・重要）'), ('bg-blue-500', '青（就職・将来）'), ('bg-green-500', '緑（学問・在学生）'), ('bg-yellow-500', '黄（お金・生活）'), ('bg-pink-500', 'ピンク（遊び・サークル）'), ('bg-gray-500', 'グレー（その他）'), ('bg-indigo-500', '紫（コラム・その他）')], default='bg-gray-500', max_length=50, verbose_name='バッジの色')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='団体名')),
                ('type', models.CharField(choices=[('lab', '研究室'), ('circle', 'サークル・部活'), ('facility', '施設・食堂'), ('dept', '学科'), ('other', 'その他')], default='lab', max_length=20, verbose_name='種類')),
                ('professor', models.CharField(blank=True, max_length=100, verbose_name='教授名')),
                ('description', models.TextField(blank=True, verbose_name='紹介文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='org_images/', verbose_name='画像')),
            ],
            options={
                'verbose_name': '団体・組織',
                'verbose_name_plural': '団体・組織',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('categories', models.ManyToManyField(related_name='blogs', to='campus_guide.category', verbose_name='カテゴリ')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus_guide.organization', verbose_name='関連団体')),
            ],
            options={
                'verbose_name': 'ブログ記事',
                'verbose_name_plural': 'ブログ記事',
                'ordering': ['-created_at'],
            },
        ),
    ]
