# Generated by Django 5.1.3 on 2025-12-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_guide', '0002_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='匿名でもOKです', max_length=50, null=True, verbose_name='お名前')),
                ('email', models.EmailField(blank=True, help_text='返信が必要な場合は入力してください', max_length=254, null=True, verbose_name='メールアドレス')),
                ('content', models.TextField(verbose_name='ご要望・お問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='お名前')),
                ('text', models.TextField(verbose_name='コメント内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='campus_guide.blog')),
            ],
        ),
    ]
