# Generated by Django 5.1.3 on 2025-09-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_guide', '0002_rename_shop_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='shop',
            new_name='university',
        ),
    ]
