# Generated by Django 5.1.3 on 2025-09-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_guide', '0003_rename_shop_blog_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university_images/'),
        ),
    ]
