# Generated by Django 5.1.3 on 2025-12-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_guide', '0003_siterequest_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'ブログ記事', 'verbose_name_plural': 'ブログ記事'},
        ),
        migrations.AddField(
            model_name='blog',
            name='priority',
            field=models.IntegerField(default=0, help_text='数字が大きいほど上に表示されます（例：100=最重要, 0=普通）', verbose_name='表示優先度'),
        ),
    ]
