# Generated by Django 5.1.3 on 2025-12-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_guide', '0004_alter_blog_options_blog_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='閲覧数'),
        ),
    ]
