# Generated by Django 5.1.3 on 2025-09-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_guide', '0005_remove_blog_university_remove_university_address_and_more'),
    ]

    operations = [
    ]
